name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build and package (Linux)
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        xvfb-run -a npm run dist:linux
    
    - name: Build and package (Windows)
      if: matrix.platform == 'win'
      run: npm run dist:win
    
    - name: Build and package (macOS)
      if: matrix.platform == 'mac'
      run: npm run dist:mac
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        draft: true
        prerelease: ${{ contains(github.ref, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}